# Generated by Django 4.0.4 on 2022-06-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='slug',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
